### ISSUE TITLE
Add DateTime to the collect-i-*.tgz file name.

### ISSUE THREAD

**Issue by hugoprudente** [awslabs/ecs-logs-collector#53]
### Summary
Add the Date Time **YYYYMMDDHHmm** to the file name, to if automated differ the time of the snapshot that the logs was collected from the same Container Instance

### Description
* Add the Date Time **YYYYMMDDHHmm** to the file name, to if automated differ the time of the snapshot that the logs was collected from the same Container Instance

**Comment by fjromerom** [comment]
I think makes more sense if we add the _datetime_ variable in the [_pack_ routine](https://github.com/hugoprudente/ecs-logs-collector/blob/master/ecs-logs-collector.sh#L239) since the _try_set_instance_collectdir_ routine is intended to discover the instance ID only:

`${tar_bin} -cvzf "$curdir/$pack_name-$datetime".tgz "$collectdir" > /dev/null 2>&1`

Additionally, we have to declare the variable [here](https://github.com/hugoprudente/ecs-logs-collector/blob/c49303efb5c5835b42ef21ebb4aa88d6a6044f6d/ecs-logs-collector.sh#L35) as follows:

```
# datetime is the date and time when the script was executed used in pack()
datetime=`date +%Y%m%d%H%M`
# pack_name is the name of the resulting tarball. This will generally
# be collect-i-fffffffffffffffff-ddddddddtttt, where i-ffffffffffffffffff is the
# instance id and ddddddddtttt is the date and time.
pack_name="collect"
```

Also remember to update the [README](https://github.com/hugoprudente/ecs-logs-collector/blob/c49303efb5c5835b42ef21ebb4aa88d6a6044f6d/README.md#usage) usage section.

On the other hand, it seems the variable _dstdir_ is not declared, let's add it [here](https://github.com/hugoprudente/ecs-logs-collector/blob/c49303efb5c5835b42ef21ebb4aa88d6a6044f6d/ecs-logs-collector.sh#L49):

```
# dstdir is the destination where the logs collected are placed.
dstdir=''  # defined in several routines
```

**Comment by Realmonia** [comment]
Fixed by @rohanmangal - thanks for the contribution!
